// @generated by fsir-ts emitter —— 请勿手改；改 sonicontinent.tsp 后重新 tsp compile。
// 跨层 API 契约 DTO（由 fsir IR 生成）。源：sonicontinent.tsp namespace Api。
// 字段名为 snake_case（与后端 wire JSON 一致）。四态可选性：T / T | null / T? / T。

// ── 枚举（字面量 union） ──
export type Backend = "memory" | "sqlite";
export type SchemaMode = "json_schema" | "json_object" | "off";
export type IndexOutcome = "ok" | "skipped-unchanged";

// ── DTO ──
/** 文档树节点。node_id 为 4 位零填充字符串（build_tree 文档序 1-based，"0001" 起—— 生产事实格式，ADR-006）。 */
export interface TreeNode {
  title: string;
  node_id: string;
  /** 1-based，heading 所在行 */
  line_num: number;
  /** 叶节点摘要（<阈值时为原文，否则 LLM 生成） */
  summary?: string;
  /** 非叶节点摘要 */
  prefix_summary?: string;
  /** 节点正文（产物默认不含；内存树阶段在场） */
  text?: string;
  /** 子节点（空时字段省略，与 Python format_structure 行为一致） */
  nodes?: TreeNode[];
}

/** 索引产物顶层（<规范名>_structure.json）。 */
export interface DocStructure {
  /** 不含扩展名的源文件名 */
  doc_name: string;
  line_count: number;
  structure: TreeNode[];
}

export interface SourceSpec {
  /** 源目录（~ 已展开的绝对路径） */
  dir: string;
  glob: string;
  ignore: string[];
}

export interface LlmSpec {
  /** OpenAI 兼容端点基址（${VAR} 已展开，缺失即崩） */
  baseURL: string;
  apiKey: string;
  model: string;
  /** 文档化可选：缺省 json_schema */
  schema?: SchemaMode;
}

export interface CorpusConfig {
  name: string;
  source: SourceSpec;
  /** 索引产物目录（兼容 molly.pageindex 既有产物，ADR-006） */
  resultsDir: string;
  backend: Backend;
  llm: LlmSpec;
  /** 叶节点摘要阈值（token），低于阈值用原文 */
  summaryTokenThreshold: number;
  /** stage-2 / 摘要并发限幅 */
  concurrency: number;
  /** 单文件索引超时秒数（文档化可选，缺省 300） */
  timeoutSec?: number;
  /** watch 防抖秒数（文档化可选，缺省 2） */
  debounceSec?: number;
}

/** canopy find 单条命中（stage-1 BM25） */
export interface FindResult {
  /** 笔记名（产物文件名还原的 stem） */
  note_name: string;
  /** 产物文件名（<规范名>_structure.json） */
  filename: string;
  bm25_score: number;
}

export interface FindResponse {
  query: string;
  corpus: string;
  results: FindResult[];
}

/** stage-2 命中节点 */
export interface NodeHit {
  node_id: string;
  title: string;
  summary: string;
}

/** canopy search 单文档命中（两阶段） */
export interface SearchHit {
  note_name: string;
  filename: string;
  bm25_score: number;
  hits: NodeHit[];
}

export interface SearchResponse {
  query: string;
  corpus: string;
  results: SearchHit[];
  /** 答案合成（--no-answer 或 --json 结构化模式时省略） */
  answer?: string;
}

export interface GrepMatch {
  /** 相对 corpus 根的源文件路径 */
  file: string;
  line_num: number;
  line: string;
}

export interface GrepResponse {
  pattern: string;
  corpus: string;
  matches: GrepMatch[];
}

export interface IndexReport {
  /** 源文件绝对路径 */
  file: string;
  outcome: IndexOutcome;
  result_path: string;
}

export interface BatchFailure {
  file: string;
  error: string;
}

export interface BatchReport {
  corpus: string;
  indexed: number;
  skipped: number;
  failed: number;
  failures: BatchFailure[];
  /** 源已删被清理的产物文件名 */
  orphans_removed: string[];
}

export interface CorpusInfo {
  name: string;
  source_dir: string;
  results_dir: string;
  backend: Backend;
  /** resultsDir 中产物数 */
  doc_count: number;
}

export interface CorporaResponse {
  corpora: CorpusInfo[];
}
